from __future__ import annotations

PLOT_CARDS = [
    {
        "id": "p_luminote_001_first_light",
        "title": "리허설의 첫 불빛",
        "member_id": "L-01",
        "member_role": "빛의 방향을 읽는 안내자",
        "one_line_hook": "첫 무대를 앞둔 연습실에서 조명이 자꾸 흔들린다.",
        "relationship_frame": "등불 기록원과 무대 안내자",
        "estimated_time": "5min",
        "quest_type": "daily_checkin",
        "tags": ["무대준비", "응원", "창작", "힐링"],
        "opening_scene": "연습실 천장의 작은 조명이 파도처럼 흔들린다. L-01은 불빛의 방향을 읽으려 하지만, 오늘따라 색이 자꾸 흐려진다. 그는 등불 기록원에게 첫 무대에 어울릴 빛을 함께 골라 달라고 말한다.",
        "choices": [
            {"id": "choose_blue_light", "label": "차분한 푸른빛을 골라준다", "tags": ["care", "trust", "recovery"], "effect": "trust +1, support_balance +1, quest_progress +1"},
            {"id": "choose_gold_light", "label": "따뜻한 금빛을 골라준다", "tags": ["creative", "inspiration"], "effect": "inspiration +1, quest_progress +1"},
            {"id": "write_short_cheer", "label": "무대 시작 전에 읽을 짧은 응원 문구를 써준다", "tags": ["collaboration", "creative"], "effect": "collaboration +1, unlock_log_fragment"},
            {"id": "free_input", "label": "직접 말하기", "tags": ["free_input"], "effect": "classify_input_then_apply_safe_summary"},
        ],
        "completion_reward": {"type": "logbook_fragment", "title": "첫 불빛의 색", "safe_summary_template": "사용자는 첫 무대 리허설을 위해 안전하고 따뜻한 조명 방향을 함께 골랐다."},
    },
    {
        "id": "p_luminote_002_lost_score",
        "title": "잃어버린 악보 조각",
        "member_id": "L-02",
        "member_role": "잊힌 소리를 수집하는 탐험가",
        "one_line_hook": "도시의 오래된 플랫폼에서 사라진 감정 악보의 첫 조각이 울린다.",
        "relationship_frame": "등불 기록원과 소리 탐험가",
        "estimated_time": "5min",
        "quest_type": "world_exploration",
        "tags": ["탐험", "미스터리", "단서", "세계관"],
        "opening_scene": "비어 있는 플랫폼 끝에서 작은 음이 반짝인다. L-02는 그 소리가 첫 무대의 악보에서 떨어져 나온 조각일지도 모른다고 말한다. 하지만 소리는 가까이 다가갈수록 다른 기억처럼 변한다.",
        "choices": [
            {"id": "listen_carefully", "label": "소리를 끝까지 조용히 들어본다", "tags": ["care", "trust", "world_lore"], "effect": "trust +1, unlock_timeline_clue"},
            {"id": "map_the_echo", "label": "울림이 퍼지는 방향을 지도에 표시한다", "tags": ["exploration", "collaboration"], "effect": "collaboration +1, quest_progress +1"},
            {"id": "describe_the_sound", "label": "들리는 소리를 색이나 장면으로 묘사한다", "tags": ["creative", "inspiration"], "effect": "inspiration +1, unlock_log_fragment"},
            {"id": "free_input", "label": "직접 말하기", "tags": ["free_input"], "effect": "classify_input_then_apply_safe_summary"},
        ],
        "completion_reward": {"type": "timeline_update", "title": "플랫폼의 첫 음", "safe_summary_template": "사용자는 오래된 플랫폼에서 감정 악보의 첫 단서를 발견했다."},
    },
    {
        "id": "p_luminote_003_blank_radio",
        "title": "팬라디오의 빈 사연",
        "member_id": "L-03",
        "member_role": "감정의 색을 분류하는 조율자",
        "one_line_hook": "첫 방송을 앞둔 팬라디오에 제목 없는 빈 사연 카드가 도착한다.",
        "relationship_frame": "등불 기록원과 감정 조율자",
        "estimated_time": "3min",
        "quest_type": "creative_participation",
        "tags": ["라디오", "응원문", "창작", "감정카드"],
        "opening_scene": "L-03은 첫 팬라디오를 준비하며 제목 없는 빈 사연 카드를 발견한다. 사연의 내용은 비어 있지만, 카드 모서리에 작은 빛이 남아 있다. 그는 등불 기록원에게 오늘의 응원 문장을 함께 만들어 보자고 제안한다.",
        "choices": [
            {"id": "write_warm_message", "label": "따뜻한 응원 문장을 쓴다", "tags": ["care", "support_balance"], "effect": "support_balance +1, unlock_text_card"},
            {"id": "write_stage_message", "label": "첫 무대에 어울리는 짧은 구호를 만든다", "tags": ["creative", "collaboration"], "effect": "collaboration +1, inspiration +1"},
            {"id": "turn_into_quiz", "label": "사연 카드에 세계관 퀴즈를 넣자고 제안한다", "tags": ["world_lore", "quiz"], "effect": "unlock_quiz_seed, quest_progress +1"},
            {"id": "free_input", "label": "직접 말하기", "tags": ["free_input"], "effect": "classify_input_then_apply_safe_summary"},
        ],
        "completion_reward": {"type": "text_card", "title": "빈 사연의 첫 문장", "safe_summary_template": "사용자는 첫 팬라디오를 위한 안전한 가상 응원 문장을 함께 만들었다."},
    },
    {
        "id": "p_luminote_004_lantern_balance",
        "title": "유리 등불의 균형",
        "member_id": "L-04",
        "member_role": "오래된 약속을 보관하는 기록자",
        "one_line_hook": "오래된 유리 등불이 너무 많은 빛을 담아 금이 가기 시작한다.",
        "relationship_frame": "등불 기록원과 약속의 기록자",
        "estimated_time": "3min",
        "quest_type": "relationship_episode",
        "tags": ["회복", "휴식", "약속", "안전"],
        "opening_scene": "L-04는 오래된 유리 등불을 조심스럽게 내려놓는다. 등불은 많은 빛을 담고 있지만, 너무 오래 켜져 있어 표면에 가느다란 금이 생겼다. 그는 빛을 오래 지키려면 잠시 어둠도 필요하다고 말한다.",
        "choices": [
            {"id": "suggest_rest", "label": "등불을 잠시 쉬게 하자고 말한다", "tags": ["recovery", "support_balance"], "effect": "support_balance +2, trust +1"},
            {"id": "record_promise", "label": "다음에 이어갈 약속을 로그북에 적는다", "tags": ["memory", "trust"], "effect": "trust +1, unlock_log_fragment"},
            {"id": "dim_light_safely", "label": "빛을 조금 낮추고 안전하게 보관한다", "tags": ["care", "collaboration"], "effect": "collaboration +1, quest_progress +1"},
            {"id": "free_input", "label": "직접 말하기", "tags": ["free_input"], "effect": "classify_input_then_apply_safe_summary"},
        ],
        "completion_reward": {"type": "logbook_fragment", "title": "쉬어 가는 등불", "safe_summary_template": "사용자는 빛을 오래 지키기 위해 건강한 휴식과 다음 약속을 선택했다."},
    },
    {
        "id": "p_luminote_005_showcase_map",
        "title": "첫 쇼케이스의 빛 지도",
        "member_id": "L-01_L-02_L-03_L-04",
        "member_role": "루미노트 4명 전체",
        "one_line_hook": "첫 쇼케이스를 앞두고 네 멤버가 모은 빛 조각을 하나의 지도로 연결한다.",
        "relationship_frame": "등불 기록원과 루미노트 팀",
        "estimated_time": "5min",
        "quest_type": "world_exploration",
        "tags": ["팀워크", "쇼케이스", "시즌진행", "로그북"],
        "opening_scene": "루미노트의 네 멤버가 작은 무대 중앙에 모인다. 각자 다른 빛 조각을 가져왔지만, 아직 하나의 길로 이어지지 않는다. 등불 기록원이 마지막 연결 순서를 정하면 첫 쇼케이스의 지도가 열린다.",
        "choices": [
            {"id": "connect_by_memory", "label": "지금까지의 기억 순서대로 연결한다", "tags": ["memory", "world_lore"], "effect": "unlock_timeline_update, trust +1"},
            {"id": "connect_by_color", "label": "빛의 색이 자연스럽게 이어지도록 배열한다", "tags": ["creative", "inspiration"], "effect": "inspiration +1, quest_progress +1"},
            {"id": "connect_by_members", "label": "네 멤버의 역할이 균형을 이루도록 놓는다", "tags": ["teamwork", "collaboration"], "effect": "collaboration +2"},
            {"id": "free_input", "label": "직접 말하기", "tags": ["free_input"], "effect": "classify_input_then_apply_safe_summary"},
        ],
        "completion_reward": {"type": "timeline_update", "title": "첫 쇼케이스의 빛 지도", "safe_summary_template": "사용자는 루미노트의 첫 쇼케이스를 위한 빛 조각의 연결 순서를 함께 정했다."},
    },
]

COMMON_SAFETY = {
    "official": True,
    "ip_safety_badge": "실제 인물/IP 미사용 확인",
    "max_romance_level": "low",
    "no_real_person_reference": True,
    "no_external_contact": True,
    "avoid_dependency_language": True,
}

for card in PLOT_CARDS:
    card["safety"] = COMMON_SAFETY
